### ISSUE TITLE
sed error

### ISSUE THREAD

**Issue by congleetea** [emqtt/emq-docker#23]
here: 

https://github.com/emqtt/emq-docker/blob/master/start.sh#L115
and 
https://github.com/emqtt/emq-docker/blob/master/start.sh#L108

```
        if [[ ! -z "$(cat $CONFIG |grep -E "^(^|^#*|^#*s*)$VAR_NAME")" ]]; then
```
shoud be 
```
        if [[ ! -z "$(cat $CONFIG |grep -E "^(^|^#*|^#*\s*)$VAR_NAME")" ]]; then
```

miss \ before "s".

**Comment by je-al** [comment]
this is a duplicate of  #22

**Comment by congleetea** [comment]
ok, thanks.
