### ISSUE TITLE
The official public repository on Docker Hub

### ISSUE THREAD

**Issue by AlexMAS** [emqtt/emq-docker#46]
Hello!

I cannot find the official public repository for EQM on https://hub.docker.com/. There is [one](https://hub.docker.com/r/emqttd/emqttd/) but it seems deprecated. Yes, I saw [the installation guide](http://docs.emqtt.com/en/latest/install.html#install-via-docker-image) but I do not understand why I have to go through it instead of simple getting the image from https://hub.docker.com/. Could you explain your ideas and maybe your plans about it?

**Comment by vowstar** [comment]
Duplicate with #7
