### ISSUE TITLE
EMQ_MQTT__MAX_PACKET_SIZE not in emq.conf

### ISSUE THREAD

**Issue by mruepp** [emqtt/emq-docker#6]
> BUG REPORT

### Expected behavior

Specifying 
EMQ_MQTT__MAX_PACKET_SIZE=128KB should be reflected in the emq.conf in the docker container.

### Actual behavior

When specifying EMQ_MQTT__MAX_PACKET_SIZE in both formats:
EMQ_MQTT__MAX_PACKET_SIZE
EMQ_MQTT_MAX_PACKET_SIZE

in docker-compose in the following variants:

environment:
  - EMQ_MQTT__MAX_PACKET_SIZE=128KB
  - EMQ_MQTT__MAX_PACKET_SIZE="128KB"
  - EMQ_MQTT_MAX_PACKET_SIZE=128KB
  - EMQ_MQTT_MAX_PACKET_SIZE="128KB"

it doesn´t get written into emq.conf into the container.

### EMQ version
Newest master

### Docker version

Which docker-engine version?

Docker version 17.03.0-ce, build 60ccb22

### System

Linux docker01.b.fir.io 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Hardware

VM

**Comment by turtleDeng** [comment]
![docker](https://cloud.githubusercontent.com/assets/1830077/24287596/42867cca-10b5-11e7-8b5e-ac7e4a877bd6.png)

`sudo docker run --rm -ti --name emq -e EMQ_MQTT__MAX_PACKET_SIZE="600KB" emq:latest`

**Comment by vowstar** [comment]
I've test, it written to config file.
